# Generated by forge sync for Forge v1.2.8; forge sync rewrites it.
for folder in /usr/local/bin /opt/homebrew/bin "$HOME/.local/bin" "$XDG_BIN_HOME" "$UV_TOOL_BIN_DIR"; do
  [ -d "$folder" ] && PATH="$folder:$PATH"
done
export PATH
if command -v forge >/dev/null 2>&1; then :
elif command -v uvx >/dev/null 2>&1; then
  forge() { uvx -q --from git+https://github.com/knacklabs/symphony-forge@v1.2.8 forge "$@"; }
else
  forge() { echo "Forge isn't installed, so this hook can't run; install it with uv tool install git+https://github.com/knacklabs/symphony-forge@v1.2.8, then run forge doctor." >&2; return 2; }
fi

# Isolate user exit/exec, and replay Git's input to both checks.
forge_husky() {
  forge_script=$1; forge_hook=$2; forge_start=$3; shift 3
  forge_input=$(mktemp) || return 2
  forge_body=$(mktemp) || { rm -f "$forge_input"; return 2; }
  cat > "$forge_input" && tail -n +"$forge_start" "$forge_script" > "$forge_body" || {
    rm -f "$forge_input" "$forge_body"; return 2;
  }
  if sh -e -c 'forge_body=$1; shift; . "$forge_body"' "$forge_script" "$forge_body" "$@" < "$forge_input"; then
    if forge hook "$forge_hook" "$@" < "$forge_input"; then forge_status=0; else forge_status=$?; fi
  else
    forge_status=$?
  fi
  rm -f "$forge_input" "$forge_body"
  return "$forge_status"
}
