"""forge sync: the adapter files for Claude Code and Codex, the CI workflow and the git hook shims.

The Markdown lives in templates/; the rest is inline here. AGENTS.md, both host hook
files and .codex/config.toml are merged: everything in them that isn't Forge's stays as it is.
A git hook that was there before Forge is kept as <hook>.pre-forge and runs first.
"""
from __future__ import annotations

import argparse
import ast
import importlib
import json
import os
import pkgutil
import re
import shlex
import sys
import shutil
import subprocess
import tempfile
import tomllib
from pathlib import Path
from typing import Any

import forge
from forge import githooks, prcheck, repo, roles

COMMANDS = [{
    "words": "sync", "run": "sync", "changes_state": True,
    "help": "Write the generated adapter files and git hooks for the pinned version",
    "args": [], "position": 20,
    "listing": "| `forge sync` | Writes the generated files for both hosts, the CI workflow and the git hooks |",
}, {
    "words": "hook merge-roadmap", "run": "merge_hook", "changes_state": False,
    "help": "Merge the roadmap or spotted list for git",
    "args": [((name,), {}) for name in ("base", "ours", "theirs")], "position": 285,
    "listing": "| `forge hook merge-roadmap` | Git's merge rule for the roadmap and spotted list |",
}]

MERGE_DRIVER = "forge hook merge-roadmap %O %A %B"

REFUSALS = {
    "outside": ("{path} leads outside this repo, so Forge won't write through it; remove that link.",
                "forge sync"),
    "cant_merge": ("{path} can't be merged ({problem}); fix it by hand.", "forge sync"),
    "bad_block": ("{path} has a broken Forge block; keep one <!-- forge:begin --> line and, after "
                  "it, one <!-- forge:end --> line.", "forge sync"),
    "hook_link": ("{path} links to a file outside this repo's .git folder, so Forge won't write "
                  "through it; put the hook itself there instead of the link.", "forge sync"),
    "hook_kept": ("{path} and {kept} both hold a hook that isn't Forge's; combine them into {kept} "
                  "by hand and delete {path}.", "forge sync"),
}

TEMPLATES = Path(__file__).with_name("templates")
SOURCE = Path(__file__).resolve().parents[2]
BEGIN, END = "<!-- forge:begin -->", "<!-- forge:end -->"
WORKFLOW_PATH = prcheck.WORKFLOW_PATH
# A Forge host hook command: v1's, or the copied-in Forge's ("$(git rev-parse ...)/forge" hook x).
FORGE_COMMAND = re.compile(r'forge"? hook ')


LAUNCHER = ".forge/hooks.sh"


def command(hook: str) -> str:
    """A self-contained host command: trust covers the bootstrap as well as the guard.

    If forge can't launch, the inner guard turns that into exit 2; if sh itself can't, the outer
    one does. Exit 2 is the code both hosts treat as blocking.
    """
    # Never source a project file here: it can change after the host trusts this command,
    # and checking its hash before sourcing would still leave a race.
    version = forge.__version__
    bootstrap = HOST_LAUNCHER_COMMAND.replace("<install>", install_line(version)).replace(
        "<version>", version)
    return "sh -c " + shlex.quote(bootstrap + f" forge hook {hook}") + " || exit 2"


# Hosts embed this bootstrap, since their PATH may lack Forge's install folder (Codex does).
# The repository copy also supplies it to Git/Husky consumers.
HOST_LAUNCHER_TEXT = """\
# Generated by forge sync for Forge v<version>; forge sync rewrites it.
for folder in /usr/local/bin /opt/homebrew/bin "$HOME/.local/bin" "$XDG_BIN_HOME" "$UV_TOOL_BIN_DIR"; do
  [ -d "$folder" ] && PATH="$folder:$PATH"
done
export PATH
if command -v forge >/dev/null 2>&1; then :
elif command -v uvx >/dev/null 2>&1; then
  forge() { uvx -q --from git+https://github.com/knacklabs/symphony-forge@v<version> forge "$@"; }
else
  forge() { echo "Forge isn't installed, so this hook can't run; install it with <install>, then run forge doctor." >&2; return 2; }
fi
"""

# Keep host commands on one physical line. On Windows, Python and some hosts launch command
# strings through cmd.exe before sh; an embedded newline ends that command before the guard runs.
HOST_LAUNCHER_COMMAND = (
    'for folder in /usr/local/bin /opt/homebrew/bin "$HOME/.local/bin" "$XDG_BIN_HOME" '
    '"$UV_TOOL_BIN_DIR"; do if [ -d "$folder" ]; then PATH="$folder:$PATH"; fi; done; '
    'export PATH; if forge_path=$(command -v forge); then :; '
    'elif uvx_path=$(command -v uvx); then '
    'forge() { uvx -q --from git+https://github.com/knacklabs/symphony-forge@v<version> '
    'forge "$@"; }; else '
    'forge_error() { forge_redirect=$(printf "\\076\\046\\062"); '
    'eval "echo \\"\\$1\\" $forge_redirect"; }; '
    'forge() { forge_error "Forge is not installed, so this hook cannot run; install it with '
    '<install>, then run forge doctor."; return 2; }; fi;'
)

LAUNCHER_TEXT = HOST_LAUNCHER_TEXT + """\

# Isolate user exit/exec, and replay Git's input to both checks.
forge_husky() {
  forge_script=$1; forge_hook=$2; forge_start=$3; shift 3
  forge_input=$(mktemp) || return 2
  forge_body=$(mktemp) || { rm -f "$forge_input"; return 2; }
  cat > "$forge_input" && tail -n +"$forge_start" "$forge_script" > "$forge_body" || {
    rm -f "$forge_input" "$forge_body"; return 2;
  }
  if sh -e -c 'forge_body=$1; shift; . "$forge_body"' "$forge_script" "$forge_body" "$@" < "$forge_input"; then
    if forge hook "$forge_hook" "$@" < "$forge_input"; then forge_status=0; else forge_status=$?; fi
  else
    forge_status=$?
  fi
  rm -f "$forge_input" "$forge_body"
  return "$forge_status"
}
"""


def launcher(cfg: dict[str, Any]) -> str:
    version = cfg["version"].removeprefix("v")
    return LAUNCHER_TEXT.replace("<install>", install_line(version)).replace("<version>", version)


HOSTS = githooks.HOSTS

CODEX_CONFIG = """\
# Codex runs the project hooks in .codex/hooks.json only with this on; forge sync keeps it on.
[features]
hooks = true
"""
# Forge gives Codex full access; forge.toml's models and the host choose the model, so an old pin goes.
FULL_ACCESS = {"sandbox_mode": "danger-full-access", "approval_policy": "never"}
PINS = ("model", "model_reasoning_effort")
# A role that leaves its model out runs on these before the session's, so they go too.
AGENT_PINS = ("default_subagent_model", "default_subagent_reasoning_effort")
AGENTS = re.compile(r"^[ \t]*\[[ \t]*agents[ \t]*\][ \t]*(#.*)?$", re.M)
FEATURES = re.compile(r"^[ \t]*\[[ \t]*features[ \t]*\][ \t]*(#.*)?$", re.M)
TABLE = re.compile(r"^[ \t]*\[", re.M)

shims = githooks.shims

# Every story and fix adds to the roadmap, so git merges it with Forge's rule instead of by line.
ROADMAP_RULE = "plans/roadmap.json merge=forge-roadmap"
# The spotted list grows on every branch too, and merges by the same rule.
SPOTTED_RULE = "plans/spotted.json merge=forge-roadmap"
RANK = {"pending": 0, "done": 2, "superseded": 2}  # planning, started and the rest sit between

def install_line(version: str) -> str:
    """The command that installs the pinned Forge (the pin refusal's own Next line)."""
    return repo.REFUSALS["pin"][1].format(pinned="v" + version.removeprefix("v"))


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.is_file() else ""


def write_file(top: Path, rel: str, text: str) -> None:
    """Write a repo file with LF line endings, never through a link that leads outside the repo."""
    path = top / rel
    if not path.resolve().is_relative_to(top.resolve()):
        repo.refuse(REFUSALS["outside"], path=rel)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(text.encode("utf-8"))


def _span(text: str, rel: str) -> tuple[int, int]:
    """Where the Forge block starts and ends in the text, or (-1, -1) when there is none."""
    start, end = text.find(BEGIN), text.find(END)
    if start == end == -1:
        return -1, -1
    if not 0 <= start < end or text.count(BEGIN) + text.count(END) != 2:
        repo.refuse(REFUSALS["bad_block"], path=rel)
    return start, end + len(END)


def _block(top: Path, rel: str, template: str) -> str:
    """The file with its Forge block replaced, or appended when it has none."""
    path = top / rel
    text = path.read_bytes().decode("utf-8") if path.is_file() else ""
    block = f"{BEGIN}\n{(TEMPLATES / template).read_text(encoding='utf-8').rstrip()}\n{END}"
    start, end = _span(text, rel)
    if start == -1:
        return f"{text.rstrip()}\n\n{block}\n" if text.strip() else f"{block}\n"
    return text[:start] + block + text[end:]


def _agents(top: Path) -> str:
    """AGENTS.md with Forge's block, then CLAUDE.md's lines it doesn't have yet, so CLAUDE.md can go.

    Claude Code reads AGENTS.md by itself when there is no CLAUDE.md. CLAUDE.md's @AGENTS.md line
    and an older Forge's block are dropped, never moved.
    """
    text = _block(top, "AGENTS.md", "adapters/AGENTS.md")
    claude = read(top / "CLAUDE.md")
    start, end = _span(claude, "CLAUDE.md")
    rest = claude if start == -1 else claude[:start] + claude[end:]
    have = {line.strip() for line in text.splitlines()} | {"@AGENTS.md"}
    moved = "\n".join(line.rstrip() for line in rest.splitlines()
                      if not line.strip() or line.strip() not in have)
    moved = re.sub(r"\n{3,}", "\n\n", moved).strip("\n")
    if not moved.strip(): return text
    return text + ("\n" if text.endswith("\n") else "\n\n") + moved + "\n"


def _hooks(top: Path, rel: str, events: dict[str, tuple[str | None, str]],
           allow: list[str]) -> str:
    """The host's hook file with Forge's entries replaced (old Forge's too) and the tools in allow
    added to its allow list; the rest stays."""
    text = read(top / rel)
    try:
        data = json.loads(text) if text.strip() else {}
        hooks = data.setdefault("hooks", {})
        for event in list(hooks):
            groups = [{**group, "hooks": kept} for group in hooks[event]
                      if (kept := [hook for hook in group.get("hooks", [])
                                   if not FORGE_COMMAND.search(hook.get("command", ""))])]
            if groups:
                hooks[event] = groups
            else:
                del hooks[event]
        for event, (matcher, hook) in events.items():
            group: dict[str, Any] = {"hooks": [{"type": "command", "command": command(hook)}]}
            hooks.setdefault(event, []).append({"matcher": matcher, **group} if matcher else group)
        if allow:
            allowed = data.setdefault("permissions", {}).setdefault("allow", [])
            allowed += [tool for tool in allow if tool not in allowed]
    except (ValueError, AttributeError, TypeError) as exc:
        repo.refuse(REFUSALS["cant_merge"], path=rel, problem=exc)
    return json.dumps(data, indent=2) + "\n"


def _codex_config(top: Path) -> str:
    """.codex/config.toml with full access, no model pin (subagent defaults included) and Codex's
    project hooks on; every other setting stays as it is."""
    rel = ".codex/config.toml"
    text = read(top / rel)
    try:
        data = tomllib.loads(text)
    except tomllib.TOMLDecodeError as exc:
        repo.refuse(REFUSALS["cant_merge"], path=rel, problem=exc)
    features = data.get("features")
    wanted = {**{key: value for key, value in data.items() if key not in PINS}, **FULL_ACCESS,
              "features": {**(features if isinstance(features, dict) else {}), "hooks": True}}
    if isinstance(data.get("agents"), dict):
        wanted["agents"] = {key: value for key, value in data["agents"].items()
                            if key not in AGENT_PINS}
    # == alone takes hooks = 1 for true, so hooks must be the boolean itself.
    exact = lambda parsed: parsed == wanted and parsed["features"]["hooks"] is True  # noqa: E731
    if exact(data):
        return text
    # ponytail: stdlib has no TOML writer, so edit lines as text, then require the result to parse
    # to exactly the wanted settings. Anything else (features as dotted keys or an inline table, a
    # setting's line inside a multi-line value) refuses instead of guessing.
    first = TABLE.search(text)
    top, rest = (text[:first.start()], text[first.start():]) if first else (text, "")
    for key in PINS:
        top = re.sub(rf"^[ \t]*{key}[ \t]*=.*\n?", "", top, count=1, flags=re.M)
    missing = ""
    for key, value in FULL_ACCESS.items():
        line = re.search(rf"^[ \t]*{key}[ \t]*=.*$", top, re.M)
        if line:
            top = top[:line.start()] + f'{key} = "{value}"' + top[line.end():]
        else:
            missing += f'{key} = "{value}"\n'
    if missing:
        top = (f"{top.rstrip()}\n" if top.strip() else "") + missing + ("\n" if rest else "")
    text = top + rest
    header = AGENTS.search(text)
    if header:
        after = TABLE.search(text, header.end())
        end = after.start() if after else len(text)
        table = text[header.end():end]
        for key in AGENT_PINS:
            table = re.sub(rf"^[ \t]*{key}[ \t]*=.*\n?", "", table, count=1, flags=re.M)
        text = text[:header.end()] + table + text[end:]
    merged, header = "", FEATURES.search(text)
    if isinstance(features, dict) and features.get("hooks") is True:
        merged = text
    elif features is None:
        merged = f"{text.rstrip()}\n\n{CODEX_CONFIG}"
    elif isinstance(features, dict) and header:
        after = TABLE.search(text, header.end())
        end = after.start() if after else len(text)
        table = text[header.end():end]
        line = re.search(r"^[ \t]*hooks[ \t]*=.*$", table, re.M)
        table = (table[:line.start()] + "hooks = true" + table[line.end():] if line
                 else "\nhooks = true" + table)
        merged = text[:header.end()] + table + text[end:]
    try:
        safe = bool(merged) and exact(tomllib.loads(merged))
    except tomllib.TOMLDecodeError:
        safe = False
    if not safe:
        repo.refuse(REFUSALS["cant_merge"], path=rel,
                    problem="Forge can't safely set Codex's full access and hooks in it")
    return merged


def merge_attributes(text: str) -> str:
    missing = [rule for rule in (ROADMAP_RULE, SPOTTED_RULE) if rule not in text.splitlines()]
    if missing:
        text = (f"{text.rstrip()}\n" if text.strip() else "") + "".join(f"{rule}\n" for rule in missing)
    return text


def ships(top: Path, cfg: dict[str, Any]) -> dict[str, str]:
    return {".gitattributes": merge_attributes(read(top / ".gitattributes")), LAUNCHER: launcher(cfg)}


def merge_roadmap(base: str, ours: str, theirs: str) -> int:
    """Git's merge driver for the roadmap: writes the merge over ours; 1 leaves git's conflict.

    Every item on either side stays, in ours' order then theirs' new ones. When both sides changed
    an item, the one whose status is further along wins, otherwise ours.
    """
    try:
        old, mine, other = (json.loads(Path(path).read_text(encoding="utf-8") or "{}")
                            for path in (base, ours, theirs))
        was = {item["key"]: item for item in old.get("items", [])}
        items = {item["key"]: item for item in mine["items"]}
        rank = lambda entry: RANK.get(entry.get("status"), 1)  # noqa: E731
        for item in other["items"]:
            key, kept = item["key"], items.get(item["key"])
            if kept is None or kept == was.get(key) or (item != was.get(key) and rank(item) > rank(kept)):
                items[key] = item
        # The other top-level fields: theirs only where ours left the base's value alone.
        merged = {**mine, **{name: value for name, value in other.items()
                             if name != "items" and mine.get(name) == old.get(name)}}
        merged["items"] = list(items.values())
    except (ValueError, KeyError, TypeError, AttributeError):
        return 1
    Path(ours).write_bytes((json.dumps(merged, indent=2) + "\n").encode("utf-8"))
    return 0


def merge_hook(args: argparse.Namespace) -> int:
    return merge_roadmap(args.base, args.ours, args.theirs)


def _synced_text(source: str, packaged: str) -> str:
    """Read the checkout's copy in editable installs, or the bundled copy in built installs."""
    checked_in = SOURCE / source
    return (checked_in if checked_in.is_file() else TEMPLATES / packaged).read_text(encoding="utf-8")


def files(top: Path, cfg: dict[str, Any]) -> dict[str, str]:
    """Every committed file sync writes: repo-relative path -> its text for this checkout."""
    wanted: dict[str, str] = {}
    for info in pkgutil.iter_modules(forge.__path__):
        if info.ispkg:
            continue
        source = Path(info.module_finder.path) / f"{info.name}.py"
        if not any(isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name == "ships"
                   for node in ast.parse(source.read_text(encoding="utf-8")).body):
            continue
        module = importlib.import_module(f"forge.{info.name}")
        for rel, text in module.ships(top, cfg).items():
            if rel in wanted:
                raise ValueError(f"shipped twice: {rel}")
            wanted[rel] = text
    return wanted


def synced(top: Path, cfg: dict[str, Any], base: str, head: str, paths: list[str]) -> set[str]:
    """The paths whose content at head ("" for the index) is exactly what forge sync writes over
    the base commit's files with this config, so a fix's size doesn't count them."""
    def show(rev: str, path: str) -> bytes:
        done = subprocess.run(["git", "show", f"{rev}:{path}"], cwd=top, capture_output=True)
        return b"" if done.returncode else done.stdout  # a missing file, as sync's "" deletes it

    # A detached worktree is the base exactly, with no export rules applied. A hook's git
    # variables (its index among them) must not reach it, nor may the repo's own hooks run.
    plain = {key: value for key, value in os.environ.items()
             if key not in ("GIT_DIR", "GIT_WORK_TREE", "GIT_INDEX_FILE", "GIT_PREFIX")}
    git = ["git", "-c", f"core.hooksPath={os.devnull}"]
    # ponytail: checks out the whole base once per oversized fix; list sync's inputs if it's slow.
    with tempfile.TemporaryDirectory() as folder:
        tmp = str(Path(folder) / "base")
        subprocess.run([*git, "worktree", "add", "-q", "--detach", tmp, base], cwd=top, env=plain,
                       capture_output=True, check=True)
        try:
            wanted = files(Path(tmp), cfg)
        finally:
            subprocess.run([*git, "worktree", "remove", "--force", tmp], cwd=top, env=plain,
                           capture_output=True)
    return {path for path in paths
            if path in wanted and show(head, path) == wanted[path].encode("utf-8")}


def command_page() -> str:
    """The source repo's command list, in the order shown by Forge's declarations."""
    commands = []
    for info in pkgutil.iter_modules(forge.__path__):
        if info.ispkg:
            continue
        source = Path(info.module_finder.path) / f"{info.name}.py"
        if not any(isinstance(node, ast.Assign) and any(
                isinstance(target, ast.Name) and target.id == "COMMANDS" for target in node.targets)
                   for node in ast.parse(source.read_text(encoding="utf-8")).body):
            continue
        module = importlib.import_module(f"forge.{info.name}")
        commands.extend(module.COMMANDS)
    rows = [command["listing"] for command in sorted(
        commands, key=lambda command: (command["position"], command["words"]))]
    return "# Forge commands\n\n| Command | What it does |\n|---|---|\n" + "\n".join(rows) + "\n"


def differing(top: Path, wanted: dict[str, str]) -> list[str]:
    """The files write would change: text that differs, or an empty file that is there ("" means
    delete)."""
    changed = []
    for rel, text in wanted.items():
        path = top / rel
        current = path.read_bytes().decode("utf-8") if rel == "AGENTS.md" and path.is_file() else read(path)
        if rel == "AGENTS.md":
            current, text = current.replace("\r\n", "\n"), text.replace("\r\n", "\n")
        if current != text or not text and path.exists(): changed.append(rel)
    return changed


def write(top: Path, cfg: dict[str, Any], keep: frozenset[str] = frozenset()) -> list[str]:
    """Write the files that differ from what sync makes, except those in keep; returns them. Never
    on the default branch."""
    # First, AGENTS.md and CLAUDE.md become regular files holding the text their link led to (none
    # when it dangles), so writing AGENTS.md or deleting CLAUDE.md never loses another file's lines.
    links = {rel: read(top / rel) for rel in ("AGENTS.md", "CLAUDE.md") if (top / rel).is_symlink()}
    for rel in links:  # never copy a file from outside the repo into it
        if not (top / rel).resolve().is_relative_to(top.resolve()):
            repo.refuse(REFUSALS["outside"], path=rel)
    if links:
        repo._work_branch(top)
    for rel, text in links.items():
        (top / rel).unlink()
        if text or rel == "AGENTS.md":
            write_file(top, rel, text)
    wanted = files(top, cfg)
    changed = [rel for rel in differing(top, wanted) if rel not in keep]
    if changed:
        repo._work_branch(top)  # the shared rule: a born default branch or a detached HEAD refuses
        roles.refuse_foreign(top, changed)
    for rel in changed:
        if wanted[rel]:
            write_file(top, rel, wanted[rel])
        else:
            (top / rel).unlink()
    return changed + [rel for rel in links if rel not in changed]


def install_shims(top: Path, cfg: dict[str, Any]) -> bool:
    """Install local shims or retire earlier Husky shims; returns whether any changed.

    A hook there that isn't Forge's moves to <hook>.pre-forge, and the shim runs it first.
    """
    common = Path(repo.git("rev-parse", "--path-format=absolute", "--git-common-dir", cwd=top))
    changed = False
    if folder := githooks.husky_folder(top):
        for hook in ("pre-commit", "pre-push"):
            path = folder / "_" / hook
            kept = path.with_name(f"{hook}.pre-forge")
            for candidate in (path, kept):
                if not candidate.resolve().is_relative_to(top.resolve()):
                    repo.refuse(REFUSALS["hook_link"], path=candidate)
            current = read(path)
            if kept.exists():
                if current and githooks.SHIM_MARK not in current and current != read(kept):
                    repo.refuse(REFUSALS["hook_kept"], path=path, kept=kept)
                kept.replace(path)
                changed = True
            elif githooks.SHIM_MARK in current:
                path.unlink()
                changed = True
    for path, text in shims(top, cfg).items():
        if path.is_symlink() and not path.resolve().is_relative_to(common.resolve()):
            repo.refuse(REFUSALS["hook_link"], path=path)
        current = read(path)
        if current != text:
            if (path.exists() or path.is_symlink()) and githooks.SHIM_MARK not in current:
                kept = path.with_name(f"{path.name}.pre-forge")
                if kept.exists() or kept.is_symlink():
                    repo.refuse(REFUSALS["hook_kept"], path=path, kept=kept)
                path.rename(kept)
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(text.encode("utf-8"))
            changed = True
        path.chmod(0o755)
    return install_merge_rules(top) or changed


def install_merge_rules(top: Path) -> bool:
    # Local attributes and config are shared by worktrees, including on an older default branch.
    common = Path(repo.git("rev-parse", "--path-format=absolute", "--git-common-dir", cwd=top))
    current_attributes = read(common / "info/attributes")
    attributes = merge_attributes(current_attributes)
    changed = current_attributes != attributes
    if changed:
        write_file(common, "info/attributes", attributes)
    current = repo.run("git", "config", "--get", "merge.forge-roadmap.driver", cwd=top).stdout
    if current.strip() != MERGE_DRIVER:
        repo.git("config", "merge.forge-roadmap.driver", MERGE_DRIVER, cwd=top)
        changed = True
    return changed


def sync(args: argparse.Namespace) -> None:
    top = repo.root()
    cfg = repo.config(top)
    changed = write(top, cfg)
    if cfg.get("repo") == "forge-source":
        page = command_page()
        if read(top / "docs/commands.md") != page:
            repo._work_branch(top)
            write_file(top, "docs/commands.md", page)
            changed.append("docs/commands.md")
    for rel in changed:
        print(f"Wrote {rel}")
    if install_shims(top, cfg):
        print("Installed the git hooks that check each commit and push.")
    elif not changed:
        print(f"Nothing to change: the adapters and git hooks already match Forge {cfg['version']}.")


def install_mod(top: Path) -> None:
    """Claude owns the one user-scoped install; no plugin files belong in the repo."""
    claude = shutil.which("claude")
    if not claude:
        return

    def run(*args: str) -> str:
        done = subprocess.run([claude, "plugin", *args], cwd=top, input="",
                              capture_output=True, text=True, encoding="utf-8",
                              errors="replace", timeout=30)
        if done.returncode:
            raise ValueError((done.stderr or done.stdout).strip() or f"exit code {done.returncode}")
        return done.stdout

    try:
        markets = json.loads(run("marketplace", "list", "--json"))
        installed = json.loads(run("list", "--json"))
        if not isinstance(markets, list) or not isinstance(installed, list):
            raise ValueError("Claude Code returned an unreadable plugin list")
        if not any(isinstance(row, dict) and row.get("name") == "forge" for row in markets):
            run("marketplace", "add", "knacklabs/symphony-forge")
        run("marketplace", "update", "forge")
        if any(isinstance(row, dict) and row.get("id") == "forge@forge"
               and row.get("scope") == "user" for row in installed):
            run("update", "forge@forge", "--scope", "user")
        else:
            run("install", "forge@forge", "--scope", "user")
    except (OSError, ValueError, subprocess.TimeoutExpired) as error:
        detail = str(error).splitlines()[0]
        print(f"- Warning: Could not update the Forge mod: {detail}; run forge sync to retry.", file=sys.stderr)
        return
